title: "Study Notes"
description: "My public notes"
baseurl: ""
url: ""

theme: minima

plugins:
    - jekyll-optional-front-matter
    - jekyll-readme-index
    - jekyll-default-layout
    - jekyll-relative-links
    - jekyll-titles-from-headings
    - jekyll-seo-tag

exclude:
    - .bundle
    - .git
    - .github
    - .gitignore
    - .jekyll-cache
    - .obsidian
    - .trash
    - _site
    - vendor
    - Gemfile
    - Gemfile.lock
    - node_modules
    - package.json
    - package-lock.json
    - README.md
    - temp.log
    - wrangler.jsonc

include:
    - .assetsignore

optional_front_matter:
  remove_original: true

relative_links:
  enabled: true
  collections: true

defaults:
    - scope:
        path: ""
        type: "pages"
      values:
        layout: "page"
