title: "Study Notes"
description: "My public notes"
baseurl: ""
url: ""

theme: minima

plugins:
    - jekyll-optional-front-matter
    - jekyll-readme-index
    - jekyll-default-layout
    - jekyll-relative-links
    - jekyll-titles-from-headings
    - jekyll-seo-tag

exclude:
    - .obsidian
    - .trash
    - vendor
    - Gemfile
    - Gemfile.lock
    - README.md

include:
    - .

optional_front_matter:
  remove_original: true

relative_links:
  enabled: true
  collections: true

defaults:
    - scope:
        path: ""
        type: "pages"
      values:
        layout: "page"